# Generated by Django 5.0.1 on 2024-01-11 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField(blank=True, null=True)),
                ('inserted_date', models.DateTimeField(auto_now_add=True)),
                ('expired_date', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
