# Generated by Django 5.0.1 on 2024-01-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_date', models.DateTimeField()),
                ('inserted_date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(editable=False, max_length=8, unique=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
