# Generated by Django 5.0.1 on 2024-01-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='sent_to',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
