# Generated by Django 5.0.1 on 2024-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_rename_active_referral_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
